server:
  host: 127.0.0.1
  port: 3000

db:
  host: 127.0.0.1
  port: 5432
  user: postgres
  password: postgres
  db-name: promotion
  connection-pool:
    max-idle-connections: 10
    max-open-connections: 100
    connection-lifetime: 3600000
local-storage:
  monitored-directory: C:\Users\germi\Desktop\import
scheduler:
  period: 10000
  days-delta: 7
  batch-size: 100
